project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - transcript.qmd
    - mode-shift-targets.qmd

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides.qmd
      - text: "Mode targets"
        href: mode-shift-targets.qmd